# Base configs
baseurl: "https://www.andrewlensen.com/photography"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_dirs: ['wildlife','landscape']
image_loc: "/images"
image_fulls_loc: "/fulls"
image_thumbs_loc: "/thumbs"

# UI configs
title: "Photography by Liam Daly"
subtitle: "See the world through my eyes!"
author: "Liam Daly"
header:
 title: "Photography"
 subtitle: "by Liam Daly"
#footer:
 #name: "Hey there, my name is Ram"
 #bio: "I am a developer and a tech aficionado from India. Love making teeny tiny apps solving tiny problems in life and now learning photography."
 #github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
#social_urls:
  #twitter: "https://www.twitter.com/ram__patra"
  #instagram: "https://www.instagram.com/ram_patra"
  #dribbble: "https://dribbble.com/rampatra"
  #linkedin: "https://in.linkedin.com/in/ram-patra"
  #github: "https://www.github.com/rampatra"

exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
#   - images/
#   
#include:
#   - images/**/thumbs/
#   - images/**/fulls/
